---
title: "MOMO - Model Lineal + Fourier + Dies Setmana"
output: html_document
date: "2024-04-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Càrrega de dades i llibreries

```{r}
library(ggplot2)
library(dplyr)
library(lubridate)
library(nimble)
library(MCMCvis)

options(lubridate.week.start = 1) # Fer que la setmana comence en dilluns
```

```{r}
# Carreguem les dades des de l'arxiu RDS
dades_momo <- readRDS("momo_selected_data_no2324.rds")

dades_momo_si2324 <- readRDS("momo_selected_data_si2324.rds")

# Generem les dates per a 2023 i els quatre primers mesos de 2024
dates_2324 <- seq(ymd("2023-01-01"), ymd("2024-04-30"), by = "day")
dates_2324 <- dates_2324[!(month(dates_2324) == 2 & day(dates_2324) == 29)]

# Creem un tibble amb les dates i els valors NA per a "defunciones_observadas"
new_data <- tibble(
  fecha_defuncion = dates_2324,
  defunciones_observadas = NA
)

# Afegim les noves dades a la tibble original
dades_momo <- bind_rows(dades_momo, new_data)
rm(dates_2324,new_data)

# Agregar les dummy variables de Dilluns a Dissabte
dades_momo <- dades_momo %>%
  mutate(DL = as.numeric(wday(fecha_defuncion) == 1),
         DM = as.numeric(wday(fecha_defuncion) == 2),
         DX = as.numeric(wday(fecha_defuncion) == 3),
         DJ = as.numeric(wday(fecha_defuncion) == 4),
         DV = as.numeric(wday(fecha_defuncion) == 5),
         DS = as.numeric(wday(fecha_defuncion) == 6))

# Agafem la columna de les defuncions
y <- dades_momo$defunciones_observadas
```

## Definició i execució del model

```{r}
codi_setmana <- nimbleCode({
    # Priors
    beta0 ~ dnorm(0, sd = 1000)
    betaL ~ dnorm(0, sd = 1000)
    
    for (i in 1:2){
      alphaF[i] ~ dnorm(0, sd = 1000)
      betaF[i] ~ dnorm(0, sd = 1000)
    }
    
    for (i in 1:6){
      betaS[i] ~ dnorm(0, sd = 1000)
    }
    
    sigma ~ dunif(0.001, 100)
    
    
    # Likelihood
    for(t in 1:length(y)) {
        mu.y[t] <- beta0 + betaL*t +
          betaS[1]*DL[t] + betaS[2]*DM[t] + betaS[3]*DX[t] +
          betaS[4]*DJ[t] + betaS[5]*DV[t] + betaS[6]*DS[t] +
          alphaF[1] * cos(2 * piVal *  yDay[t] / 365) + 
          betaF[1] * sin(2 * piVal *  yDay[t] / 365) + 
          alphaF[2] * cos(4 * piVal *  yDay[t] / 365) + 
          betaF[2] * sin(4 * piVal *  yDay[t] / 365)
        
        y[t] ~ dnorm(mu.y[t], sd = sigma)
    }
    
    for (t in 1:length(y)){
      y_pstr[t] ~ dnorm(mu.y[t], sd = sigma)
    }
})

# De 2015 a 2022 + 2023 + 4 mesos 2024
yD <- c(rep(1:365, 9), 1:120)

start_time <- Sys.time()

mcmc_output <- nimbleMCMC(codi_setmana, data = list(y = y, yDay = yD, DL = dades_momo$DL, DM = dades_momo$DM, DX = dades_momo$DX, DJ = dades_momo$DJ, DV = dades_momo$DV, DS = dades_momo$DS),
                           constants = list(piVal = pi),
                           monitors = c("beta0", "alphaF", "betaF", "betaL", "betaS", "y_pstr"), 
                           niter = 10000,
                           nburnin = 1000,
                           thin = 4,
                           nchains = 2)

end_time <- Sys.time()

temps_comp <- end_time - start_time

print(temps_comp)
```

## Visualització de resultats

### Resum de dades

```{r}
MCMCplot(mcmc_output, params = c("beta0", "betaL", "alphaF", "betaF", "betaS"))
MCMCtrace(mcmc_output, pdf = FALSE, params = c("beta0", "betaL", "alphaF", "betaF", "betaS"))
MCMCsummary(mcmc_output, params = c("beta0", "betaL", "alphaF", "betaF", "betaS"))
```

### Gràfiques i errors quadràtics

```{r}
# Posterior i bandes de y_pstr
quant1 <- function(x) {
  q1 <- quantile(x,0.025)
  return(as.numeric(q1))
}

quant3 <- function(x) {
  q3 <- quantile(x,0.975)
  return(as.numeric(q3))
}

y_pstr <- unlist(MCMCpstr(mcmc_output, params = "y_pstr"))
y_est_q1 <- unlist(MCMCpstr(mcmc_output, params = "y_pstr", func = quant1))
y_est_q3 <- unlist(MCMCpstr(mcmc_output, params = "y_pstr", func = quant3))

y_est <- c(y_pstr[1:2920], rep(NA, length(y)-2920))
y_pred <- c(rep(NA, 2920), y_pstr[2921:length(y_pstr)])

dades_pstr <- dades_momo_si2324
dades_pstr$y_est <- y_est
dades_pstr$y_pred <- y_pred
dades_pstr$y_est_q1 <- y_est_q1
dades_pstr$y_est_q3 <- y_est_q3

# Gràfica de dades i línia de regressió + intervals de credibilitat
ggplot(data = dades_pstr, aes(x = fecha_defuncion, y = defunciones_observadas)) +
  geom_point(color = "brown3") +
  geom_line(aes(y = y_est), color = "blue", linewidth = 1) +
  geom_line(aes(y = y_pred), color = "green", linewidth = 1) +
  geom_ribbon(aes(ymin = y_est_q1, ymax = y_est_q3), alpha = 0.3) +
  labs(
    x = "Data de Registre", 
    y = "Nombre de Morts",
    title = "Model amb Tendències Setmanals",
    subtitle = "Predicció en bloc"
  ) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme(
    plot.title = element_text(face = "bold")
  )
```

```{r}
ggsave("grafica-setmanal-bloc-general.pdf", width = 10, height = 7)
```


```{r}
# Càlcul del EQM (Error Quadràtic Mitjà) - d'ajust
df1 <- dades_pstr[year(dades_pstr$fecha_defuncion) <= 2022, ]

EQM <- mean((df1$defunciones_observadas - df1$y_est)^2)

cat("Obtenim un error quadràtic mitjà d'ajust de EQM =", EQM)
```


```{r}
# Gràfica de dades i línia de regressió - DETALL 2023-2024

df_detall <- dades_pstr%>%
  filter(year(fecha_defuncion) %in% c(2023,2024))

ggplot(data = df_detall, aes(x = fecha_defuncion, y = defunciones_observadas)) +
  geom_point(color = "brown3") +
  geom_line(aes(y = y_pred), color = "green", linewidth = 1) +
  geom_ribbon(aes(ymin = y_est_q1, ymax = y_est_q3), alpha = 0.3) +
  labs(
    x = "Data de Registre", 
    y = "Nombre de Morts",
    title = "Model amb Tendències Setmanals",
    subtitle = "Predicció en bloc (Detall 2023-2024)"
  ) +
  scale_x_date(date_breaks = "2 months", date_labels = "%m/%y") +
  theme(
    plot.title = element_text(face = "bold")
  )
```

```{r}
ggsave("grafica-setmanal-bloc-detall.pdf", width = 10, height = 7)
```


```{r}
# Càlcul del EQMP (Error Quadràtic Mitjà de Predicció)
df2 <- dades_pstr[year(dades_pstr$fecha_defuncion) > 2022, ]

EQMP <- mean((df2$defunciones_observadas - df2$y_pred)^2)

cat("Obtenim un error quadràtic mitjà de predicció de EQMP =", EQMP)
```

